### ISSUE TITLE
声明文件报错

### ISSUE THREAD

**Issue by finch001** [Adherentman/Typescript-wxApi.d.ts#11]
wx.d.ts:21:5 - error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.

21     (res: ZeroParamVoidFunc);
       ~~~~~~~~~~~~~~~~~~~~~~~~~

wx.d.ts:636:5 - error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.

636     (callback: createInnerAudioContextonErrorRes);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

wx.d.ts:3247:18 - error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.

3247     onAppShow: { (res: WxApplicationProps) };

**Comment by Adherentman** [comment]
@finch001  抱歉那么久才回复，
![image](https://user-images.githubusercontent.com/26477346/56261164-8b88a200-610c-11e9-88a2-a530421fe78a.png)
![image](https://user-images.githubusercontent.com/26477346/56261209-bc68d700-610c-11e9-8d38-4019b2503fce.png)
![image](https://user-images.githubusercontent.com/26477346/56261222-c5f23f00-610c-11e9-8236-f0e7852582ca.png)
建议下载最新的`wx.d.ts`我在3.12以后的commit中修复了
