### ISSUE TITLE
Need not to declare `require` function for d.ts?

### ISSUE THREAD

**Issue by zxj5470** [Adherentman/Typescript-wxApi.d.ts#12]
# ISSUE
I think we need to add this declaration:
```typescript
declare function require(path: string): any;
```

## Link（API官方链接）
https://developers.weixin.qq.com/miniprogram/dev/reference/api/require.html

## ScreenShot
![image](https://user-images.githubusercontent.com/20026798/59152052-95c17f80-8a6f-11e9-9578-b20e0f3e0bf9.png)

and I  add it
![image](https://user-images.githubusercontent.com/20026798/59152057-a540c880-8a6f-11e9-8443-14d956f72e95.png)

then
![image](https://user-images.githubusercontent.com/20026798/59152060-ad006d00-8a6f-11e9-9bfa-6709a14ec028.png)

**Comment by Adherentman** [comment]
这`require`你可以通过`import util from '../../utils/util'`实现吗？

**Comment by zxj5470** [comment]
> 这`require`你可以通过`import util from '../../utils/util'`实现吗？

我只是想表达缺少这个 API，和 import 不 import 没有关系。而且文档中其实是有提及的。

![image](https://user-images.githubusercontent.com/20026798/59365224-c6086700-8d6a-11e9-894d-bcc087d59881.png)

**Comment by Adherentman** [comment]
> > 这`require`你可以通过`import util from '../../utils/util'`实现吗？
> 
> 我只是想表达缺少这个 API，和 import 不 import 没有关系。而且文档中其实是有提及的。唔……签名应该是`any require(string path)`
> 
> https://developers.weixin.qq.com/miniprogram/dev/reference/api/require.html
> 
> ![image](https://user-images.githubusercontent.com/20026798/59365224-c6086700-8d6a-11e9-894d-bcc087d59881.png)

ok，今天补上，没注意到这个里文档更新了

**Comment by Adherentman** [comment]
@zxj5470 
https://github.com/Adherentman/Typescript-wxApi.d.ts/commit/150266d5ad27380f13b3dea479811786cd27158d

**Comment by zxj5470** [comment]
emmmm……然后突然发现好像还有一个 Component 和 Behavior 的 API
