### ISSUE TITLE
wx.shareAppMessage这个接口没有提示

### ISSUE THREAD

**Issue by kulipo** [Adherentman/Typescript-wxApi.d.ts#13]
# ISSUE

## Describe the bug（描述错误）
使用时，发现微信的主动分享的接口shareAppMessage没有被包含在里面。

## Link（API官方链接）
https://developers.weixin.qq.com/minigame/dev/api/share/wx.shareAppMessage.html

**Comment by Adherentman** [comment]
已经更新，谢谢。最近太忙没时间管理了。。
