### ISSUE TITLE
ToastParam 的 icon 属性里面没有 none 这个选项

### ISSUE THREAD

**Issue by StarkShang** [Adherentman/Typescript-wxApi.d.ts#5]
如题

**Comment by Adherentman** [comment]
@StarkShang  wx.showToast(OBJECT) 这个API吗

icon | String | 否 | 图标，有效值 "success", "loading", "none"

https://developers.weixin.qq.com/miniprogram/dev/api/api-react.html

**Comment by StarkShang** [comment]
是的，但是这边源码里面没有。我自己添加后使用了

**Comment by Adherentman** [comment]
@StarkShang ok可能是后来官方加的，我最近也对文档做了更新
